// ============================================================
// JOHOR ADUN — 56 Kawasan DUN Data
// State boundary + sub-region mapping for click behavior
// ============================================================

const JOHOR_DUN = [
  {code:"J01", name:"Buloh Kasap", parlimen:"P140 Segamat", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J02", name:"Jementah", parlimen:"P140 Segamat", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Naik 3%"},
  {code:"J03", name:"Pemanis", parlimen:"P140 Segamat", color:"#f0c040", alerta:"1", sentimen:"Sederhana", trend:"Naik 8%"},
  {code:"J04", name:"Kemelah", parlimen:"P141 Sekijang", color:"#f0c040", alerta:"1", sentimen:"Sederhana", trend:"Turun 2%"},
  {code:"J05", name:"Tenang", parlimen:"P141 Sekijang", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J06", name:"Bekok", parlimen:"P142 Labis", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J07", name:"Bukit Kepong", parlimen:"P142 Labis", color:"#f0c040", alerta:"1", sentimen:"Sederhana", trend:"Naik 5%"},
  {code:"J08", name:"Bukit Pasir", parlimen:"P143 Pagoh", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Turun 1%"},
  {code:"J09", name:"Gambir", parlimen:"P143 Pagoh", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J10", name:"Tangkak", parlimen:"P144 Ledang", color:"#f0c040", alerta:"1", sentimen:"Sederhana", trend:"Naik 2%"},
  {code:"J11", name:"Serom", parlimen:"P144 Ledang", color:"#ff4d6a", alerta:"2", sentimen:"Kritikal", trend:"Naik 12%"},
  {code:"J12", name:"Bentayan", parlimen:"P145 Bakri", color:"#ff4d6a", alerta:"2", sentimen:"Kritikal", trend:"Naik 15%"},
  {code:"J13", name:"Simpang Jeram", parlimen:"P145 Bakri", color:"#f0c040", alerta:"1", sentimen:"Sederhana", trend:"Naik 6%"},
  {code:"J14", name:"Bukit Naning", parlimen:"P145 Bakri", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J15", name:"Maharani", parlimen:"P146 Muar", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Turun 3%"},
  {code:"J16", name:"Sungai Balang", parlimen:"P146 Muar", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J17", name:"Semerah", parlimen:"P147 Parit Sulong", color:"#f0c040", alerta:"1", sentimen:"Sederhana", trend:"Naik 4%"},
  {code:"J18", name:"Sri Medan", parlimen:"P147 Parit Sulong", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J19", name:"Yong Peng", parlimen:"P148 Ayer Hitam", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J20", name:"Semarang", parlimen:"P148 Ayer Hitam", color:"#ff4d6a", alerta:"2", sentimen:"Kritikal", trend:"Naik 10%"},
  {code:"J21", name:"Parit Yaani", parlimen:"P149 Sri Gading", color:"#f0c040", alerta:"1", sentimen:"Sederhana", trend:"Turun 2%"},
  {code:"J22", name:"Parit Raja", parlimen:"P149 Sri Gading", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J23", name:"Penggaram", parlimen:"P150 Batu Pahat", color:"#ff4d6a", alerta:"3", sentimen:"Panik", trend:"Naik 20%"},
  {code:"J24", name:"Senggarang", parlimen:"P150 Batu Pahat", color:"#f0c040", alerta:"1", sentimen:"Sederhana", trend:"Naik 3%"},
  {code:"J25", name:"Rengit", parlimen:"P151 Simpang Renggam", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J26", name:"Machap", parlimen:"P151 Simpang Renggam", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J27", name:"Layang-Layang", parlimen:"P152 Kluang", color:"#f0c040", alerta:"1", sentimen:"Sederhana", trend:"Naik 5%"},
  {code:"J28", name:"Mengkibol", parlimen:"P152 Kluang", color:"#ff4d6a", alerta:"2", sentimen:"Kritikal", trend:"Naik 11%"},
  {code:"J29", name:"Mahkota", parlimen:"P152 Kluang", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J30", name:"Paloh", parlimen:"P153 Sembrong", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J31", name:"Kahang", parlimen:"P153 Sembrong", color:"#f0c040", alerta:"1", sentimen:"Sederhana", trend:"Naik 2%"},
  {code:"J32", name:"Endau", parlimen:"P154 Mersing", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J33", name:"Tenggaroh", parlimen:"P154 Mersing", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J34", name:"Panti", parlimen:"P155 Tenggara", color:"#f0c040", alerta:"1", sentimen:"Sederhana", trend:"Turun 1%"},
  {code:"J35", name:"Pasir Raja", parlimen:"P155 Tenggara", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J36", name:"Sedili", parlimen:"P156 Kota Tinggi", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J37", name:"Johor Lama", parlimen:"P156 Kota Tinggi", color:"#f0c040", alerta:"1", sentimen:"Sederhana", trend:"Naik 4%"},
  {code:"J38", name:"Penawar", parlimen:"P157 Pengerang", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J39", name:"Tanjung Surat", parlimen:"P157 Pengerang", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J40", name:"Tiram", parlimen:"P158 Tebrau", color:"#ff4d6a", alerta:"2", sentimen:"Kritikal", trend:"Naik 14%"},
  {code:"J41", name:"Puteri Wangsa", parlimen:"P158 Tebrau", color:"#f0c040", alerta:"1", sentimen:"Sederhana", trend:"Naik 7%"},
  {code:"J42", name:"Johor Jaya", parlimen:"P159 Pasir Gudang", color:"#ff1744", alerta:"3", sentimen:"Panik", trend:"Naik 18%"},
  {code:"J43", name:"Permas", parlimen:"P159 Pasir Gudang", color:"#ff4d6a", alerta:"2", sentimen:"Kritikal", trend:"Naik 13%"},
  {code:"J44", name:"Larkin", parlimen:"P160 Johor Bahru", color:"#ff4d6a", alerta:"2", sentimen:"Kritikal", trend:"Naik 9%"},
  {code:"J45", name:"Stulang", parlimen:"P160 Johor Bahru", color:"#f0c040", alerta:"1", sentimen:"Sederhana", trend:"Naik 3%"},
  {code:"J46", name:"Perling", parlimen:"P161 Pulai", color:"#f0c040", alerta:"1", sentimen:"Sederhana", trend:"Naik 5%"},
  {code:"J47", name:"Kempas", parlimen:"P161 Pulai", color:"#ff4d6a", alerta:"2", sentimen:"Kritikal", trend:"Naik 16%"},
  {code:"J48", name:"Skudai", parlimen:"P162 Iskandar Puteri", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J49", name:"Kota Iskandar", parlimen:"P162 Iskandar Puteri", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J50", name:"Bukit Permai", parlimen:"P163 Kulai", color:"#f0c040", alerta:"1", sentimen:"Sederhana", trend:"Naik 6%"},
  {code:"J51", name:"Bukit Batu", parlimen:"P163 Kulai", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J52", name:"Senai", parlimen:"P164 Pontian", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J53", name:"Benut", parlimen:"P164 Pontian", color:"#f0c040", alerta:"1", sentimen:"Sederhana", trend:"Naik 4%"},
  {code:"J54", name:"Pulai Sebatang", parlimen:"P165 Tanjung Piai", color:"#f0c040", alerta:"1", sentimen:"Sederhana", trend:"Naik 2%"},
  {code:"J55", name:"Pekan Nanas", parlimen:"P165 Tanjung Piai", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"},
  {code:"J56", name:"Kukup", parlimen:"P165 Tanjung Piai", color:"#00d4a0", alerta:"0", sentimen:"Aman", trend:"Stabil"}
];

JOHOR_DUN.lookup = {};
JOHOR_DUN.forEach(d => { JOHOR_DUN.lookup[d.code] = d; });
